### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by argyleink** [serheyShmyg/grunt-jade-inheritance#1]
![screen shot 2015-01-27 at 7 43 58 pm](https://cloud.githubusercontent.com/assets/1134620/5932130/e6b41dd6-a65c-11e4-800e-4fc2c650f619.png)

Just spent an hour trying to use this tool. I've configured many plugins, but this one nor the jade-inheritance npm module work. Do you have a test bed where I can try your solution?

**Comment by argyleink** [comment]
the "files" the watch function is running, is empty. It's almost like you need to update the custom debounce function to a newer version of grunt? i'm very certain i had the configuration right, but the jade-inheritance function you borrowed isn't working anymore. should i move the bug to his repo?

**Comment by argyleink** [comment]
turns out my issue was i broke my tasks out to a separate files, and the configs arent loaded with your grunt function.

**Comment by mishelen** [comment]
I'm too.
don't understand, how to set it up in the case of separate tasks (load-grunt-config). Does this available?

**Comment by argyleink** [comment]
I made a pull request that resolves this issue. You can try my fork if you want.

**Comment by mishelen** [comment]
Thank You, Adam. I have seen and even tried just did not work. In general, the problem is that we use different plugins to divide tasks -- yes they even almost equally called (_load-grunt-config_ and _load-grunt-configs_), but the structure of tasks different.

You expanded the function in case of yours tasks, at the same time respecting the structure of the project for your plugin, I would correct itself, but I examine JavaScript a couple of months((.

**Comment by brunowego** [comment]
+1
